### PR TITLE
gitlab: add missing `signin_required` decorator

### PR DESCRIPTION
**Pull request by mvidalgarcia**

### CODE REVIEW

**Review by diegodelemos — APPROVED** [review]

**Comment by diegodelemos** [comment]
@mvidalgarcia  Have you searched to see if we are missing the same decorator somewhere else?
E.g.
```console
reana_server/rest/gitlab.py:@blueprint.route("/gitlab/connect")
reana_server/rest/gitlab.py-def gitlab_connect():
reana_server/rest/gitlab.py-    r"""Endpoint to init the REANA connection to GitLab.
```

**Comment by mvidalgarcia** [comment]
> @mvidalgarcia Have you searched to see if we are missing the same decorator somewhere else?
> E.g.
> 
> ```
> reana_server/rest/gitlab.py:@blueprint.route("/gitlab/connect")
> reana_server/rest/gitlab.py-def gitlab_connect():
> reana_server/rest/gitlab.py-    r"""Endpoint to init the REANA connection to GitLab.
> ```

That endpoint never had checks to verify if the user is authenticated, that's why is lacking the decorator. But actually, I think it makes sense to protect it even though we don't use the authenticated user object. What do you think?

**Comment by mvidalgarcia** [comment]
Other endpoints that are not protected:

- `/api/config` - I think we need it for the UI so we can display SSO/local users forms before authentication.
- `/api/ping` - for obvious reasons

**Comment by diegodelemos** [comment]
We can protect all the mentioned ones except `/api/ping` which we use for health checks.

**Comment by mvidalgarcia** [comment]
I think we can't protect `/config` because otherwise, we don't know whether we should display SSO login, local users login or both. In any case, we're not exposing anything critical there.

**Pull request merged**
